language: node_js
cache:
  directories:
    # https://twitter.com/maybekatz/status/905213355748720640
    - ~/.npm

node_js:
  # https://medium.com/@mikeal/stop-supporting-old-releases-70cfa0e04b0c
  - "lts/*"

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1

script:
  - npm run coverage

before_script:
  - greenkeeper-lockfile-update
  - npm prune

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - npm run travis-deploy-once "npx sync-glitch-cli"

# Deploy coverage report to GitHub Pages
deploy:
  provider: pages
  local-dir: "coverage/lcov-report"
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

notifications:
  email: false
