language: node_js

cache:
  directories:
    # https://twitter.com/maybekatz/status/905213355748720640
    - ~/.npm

notifications:
  email: false

node_js:
  - '8'

before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update
  - npm prune

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - npm run semantic-release

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper
