language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '10'
  - '9'
  - '8'

before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1

script:
  - npm run coverage

before_script:
  - greenkeeper-lockfile-update
  - npm prune

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - npm run travis-deploy-once "npx sync-glitch"

deploy:
  provider: pages
  local-dir: "coverage/lcov-report"
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

branches:
  only:
    - master
    - /^greenkeeper/.*$/
