version: 2.1
jobs:
  build:
    working_directory: ~/usr/src/app
    docker:
      - image: circleci/node:lts
    steps:
      - checkout

      - run:
          name: update npm
          command: sudo npm install -g npm@latest

      - restore_cache:
          name: Restore npm dependencies
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-{{ .Branch }}-
            - dependency-cache-

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          name: Save npm dependencies
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/usr/src/app/node_modules

      - run:
          name: test
          command: npm test

      - store_artifacts:
          name: Store artifacts
          path: coverage
