version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts

    steps:
      - checkout

      - run:
          name: Check current version of Node
          command: node -v

      - run:
          name: Check current version of NPM
          command: npm -v

      - run:
          name: Install node modules
          command: npm i

      - run:
          name: Run test
          command: npm run test

workflows:
  version: 2
  workflow:
    jobs:
      - build

# Workaround
# To filter notification triggers based on branch(es) but it is undocumented way
# see: https://discuss.circleci.com/t/only-notify-for-some-branches/10244
experimental:
  notify:
    branches:
      only:
        - master
